In [1]:
import pandas as pd
import numpy as np
import Variables
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('../BNB_nue data/test_output.csv')
df = df[['event', 'id', 'x', 'z']]
df.head()

event  id        x       z
0      1   1  120.251  846.55
1      1   1  120.217  846.85
2      1   1  120.155  847.15
3      2   1  119.384  846.25
4      2   1  119.300  846.55

In [3]:
nHits = Variables.get_nHits(df)
nHits

[3, 41, 22, 13, 247, 136, 21]

In [4]:
rss= Variables.RSS(df)
rss

[0.0016544738323074001,
 0.01049799244192176,
 0.012378601934623869,
 0.0033822302452935333,
 47.84812845124709,
 1.3310935411260039,
 0.030436490485585204]

In [5]:
pc2VarExplained = Variables.pc2VarExplained(df)
pc2VarExplained

[array([0.00694183]),
 array([0.00020834]),
 array([0.00085502]),
 array([0.00067153]),
 array([0.03902095]),
 array([0.00171074]),
 array([0.00231114])]